


all:
	@./makepage.sh accomodation
	@./makepage.sh attending
	@./makepage.sh cfp
	@./makepage.sh cultural
	@./makepage.sh index
	@./makepage.sh org
	@./makepage.sh pc
	@./makepage.sh photos
	@./makepage.sh program
